apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vandalizem
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: vandalizem
    newName: rg.fr-par.scw.cloud/djnd/vandalizem
    newTag: '6bd8caccae4f06b065057f8f910fa8b0ef71877b'
