apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vandalizem
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: vandalizem
    newName: rg.fr-par.scw.cloud/djnd/vandalizem
    newTag: '370498ccc1e28c6f59f95e9f890a4e3468127f2a'
